# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  mydate: $(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)
  branch: master

# name: $(branch)
# name: $(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds) - "Prueba-Master"
# name: $(mydate)-$(branch)
name: $(Date:yyyyMMdd)-$(Hours:HH)$(Minutes:mm)$(Seconds:ss)-$(branch)

pool:
  vmImage: ubuntu-latest
  name: Default
  demands:
  - Agent.name -equals windows-10-agent-01

steps:
- script: echo Hello, world!
  displayName: 'Master - Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo Master Branckh
  displayName: 'Master - Run a multi-line script'
