# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  mydate: $[format('{0:yyyy}-{0:MM}-{0:dd}T{0:HH}:{0:mm}:{0:ss}', pipeline.startTime)]
  branch: master

# name: $(branch)
name: "Prueba"

pool:
  vmImage: ubuntu-latest
  name: Default
  demands:
  - Agent.name -equals windows-10-agent-01

steps:
- script: echo Hello, world!
  displayName: 'Master - Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo Master Branckh
  displayName: 'Master - Run a multi-line script'
